name: Infra Construction And App Deploy

on:
  workflow_dispatch:

jobs:
  Build:
    name: Deploy Infra and Build
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Update Parameter in APP Config
        run: |
          sed -i "s|{tmp_client_secret_key}|${{ secrets.SP_CLIENT_SECRET_KEY }}|g" config.py
          sed -i "s|{tmp_db_server_name}|${{ secrets.DB_SERVER_NAME }}|g" config.py
          sed -i "s|{tmp_db_server_user}|${{ secrets.DB_SERVER_USER }}|g" config.py
          sed -i "s|{tmp_db_server_password}|${{ secrets.DB_SERVER_PASSWORD }}|g" config.py
          sed -i "s|{tmp_db_name}|${{ secrets.DB_NAME }}|g" config.py

          sed -i "s|{tmp_storage_account_name}|${{ secrets.STORAGE_ACCOUNT }}|g" config.py
          sed -i "s|{tmp_storage_container_name}|${{ secrets.STORAGE_CONTAINER }}|g" config.py

          sed -i "s|{tmp_storage_key}|${{ secrets.STORAGE_KEY }}|g" config.py
          sed -i "s|{tmp_sp_client_id}|${{ secrets.SP_CLIENT_ID }}|g" config.py
          sed -i "s|{tmp_sp_client_secret}|${{ secrets.SP_CLIENT_SECRET }}|g" config.py
          cat config.py

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  DeployApp:
    runs-on: ubuntu-latest
    needs: InitDatabase
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SP_CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ secrets.APP_NAME }}
          slot-name: 'Production'
