name: Test

on:
  workflow_dispatch:

jobs:
  DeployApp:
    runs-on: ubuntu-latest 
    needs: InitDatabase
    permissions:
      id-token: write

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Depencencies
        run: |
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SP_CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Web App'
        run: |
          az webapp up --runtime PYTHON:3.9 --sku B1 --logs
